#!/bin/bash


head -12 readme.md

echo "# == Что нас привело к исследованию? =="
echo ""
echo "##### Однажды, стало интересно, что такое ДНК код человека через {программирование}. Нашли пару дельных репозиториев на GitHub -> fork — нув их начали исследовать код. Теперь делимся с вами нашим исследованием. "
echo
echo "# == НАША ЦЕЛЬ =="
echo
echo "- Создать набор открытых данных по ДНК. "
echo "- Научиться обрабатывать данные ДНК. "
echo "-  "
echo "- Структурирование информации в машиночитаемый вид"
echo 

echo "# Данные по НПЗ России"
echo

for npz in `ls NPZ/NPZ.md`
do
  echo
  cat NPZ/NPZ.md/$npz
done


tail -29 readme.md

echo "# Приложение 1. Карты."
cat archive/Maps/readme.md | awk '{ gsub("\\]\\(","](archive/Maps/"); print }'

echo "# Приложение 2. Датасет по НПЗ России."

echo "\`\`\`json"
cat NPZ/NPZ.json/NPZ.json
echo "\`\`\`"


